Project_Five/AppFive/urls.py
from django.conf.urls import url
from AppFive import views

#TEMPLATE URLs
app_name = 'AppFive'

urlpatterns=[
    url('registeration/',views.register,name='registeration'),
    url('user_login/',views.user_login,name='user_login'),
]

Project_Five/Project_Five/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from AppFive import views
urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('AppFive/',include('AppFive.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')

]

Project_Five/AppFive/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional class
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

Project_Five/AppFive/forms.py
from django import forms
from django.contrib.auth.models import User
from AppFive.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Project_Five/AppFive/views.py
from django.shortcuts import render
from AppFive.forms  import UserForm,UserProfileInfoForm
#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'AppFive/index.html')

@login_required
def special(request):
    return HttpResponse("You are Logged in. Congrats")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'AppFive/registeration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request,'AppFive/login.html',{})

Project_Five/templates/AppFive/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class='nav navbar-nav'>
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'AppFive:registeration' %}">Registration</a></li>

          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>

          {% else %}
          <li><a class="navbar-link" href="{% url 'AppFive:user_login' %}">Login</a></li>

          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

Project_Five/templates/AppFive/index.html
{% extends "AppFive/base.html"%}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    <em><h1>This Is the HOME PAGE.</h1></em>
</div>
{% endblock %}

Project_Five/templates/AppFive/login.html
{% extends "AppFive/base.html"%}
{% load static %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'AppFive:user_login' %}" method="POST">
      {% csrf_token %}
      <label for="username">Username: </label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password: </label>
      <input type="password" name="password" placeholder="***">
      <input type="submit" class="btn btn-default" value="Login">
    </form>
  </div>
{% endblock %}

Project_Five/templates/AppFive/registeration.html
{% extends "AppFive/base.html"%}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for Registeration.</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form: </h3>

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token%}
      {{ user_form.as_p }}
      {{profile_form.as_p}}
      <input type="submit" class='btn btn-success' value="Register">
    </form>
  {% endif%}

</div>
{% endblock %}